Upgrade miso & gocommon

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -2,27 +2,38 @@
 
 # --------- remote
 remote="alphaboi@curtisnewbie.com"
-remote_build_path="~/services/mini-fstore/build/"
-remote_config_path="~/services/mini-fstore/config/"
+service="mini-fstore"
+remote_build_path="~/services/${service}/build/"
+remote_config_path="~/services/${service}/config/"
+os="linux"
+arch="amd64"
+build="${service}_build"
+dockerfile="./Dockerfile_local"
 # ---------
 
-ssh  "alphaboi@curtisnewbie.com" "rm -rv ${remote_build_path}*"
+echo "Building Go app for platform $os/$arch to binary '$build'"
+CGO_ENABLED=0 GOOS="$os" GOARCH="$arch" go build -o "$build"
 
-rsync -av -e ssh  --exclude='.git' \
-    --exclude='storage' \
-    --exclude='trash' \
-    --exclude='.vscode' \
-    --exclude='schema' \
-    --exclude='LICENSE' \
-    --exclude='README.md' \
-    ./* "${remote}:${remote_build_path}"
-if [ ! $? -eq 0 ]; then
-    exit -1
-fi
+ssh  "alphaboi@curtisnewbie.com" "rm -rv ${remote_build_path}*"
 
 rsync -av -e ssh ./app-conf-prod.yml "${remote}:${remote_config_path}"
 if [ ! $? -eq 0 ]; then
     exit -1
 fi
 
-ssh  "alphaboi@curtisnewbie.com" "cd services; docker-compose up -d --build mini-fstore"
+rsync -av -e ssh "./$build" "${remote}:${remote_build_path}"
+if [ ! $? -eq 0 ]; then
+    exit -1
+fi
+
+rsync -av -e ssh "./$dockerfile" "${remote}:${remote_build_path}/Dockerfile"
+if [ ! $? -eq 0 ]; then
+    exit -1
+fi
+
+ssh  "alphaboi@curtisnewbie.com" "cd services; docker-compose up -d --build ${service}"
+
+# cleanup
+if [ -f "$build" ]; then
+    rm "$build"
+fi
